name: Deploy Artifacts to GitHub Packages

on: workflow_dispatch

jobs:
  setup-and-publish:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            tasks: publishAndroidReleasePublicationToGitHubPackagesRepository publishJvmPublicationToGitHubPackagesRepository publishJsPublicationToGitHubPackagesRepository publishKotlinMultiplatformPublicationToGitHubPackagesRepository
          - os: macos-latest
            tasks: publishIosArm64PublicationToGitHubPackagesRepository publishIosX64PublicationToGitHubPackagesRepository publishMacosArm64PublicationToGitHubPackagesRepository publishMacosX64PublicationToGitHubPackagesRepository publishTvosArm64PublicationToGitHubPackagesRepository publishTvosX64PublicationToGitHubPackagesRepository publishWatchosArm32PublicationToGitHubPackagesRepository publishWatchosArm64PublicationToGitHubPackagesRepository publishWatchosX64PublicationToGitHubPackagesRepository

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Linux-specific Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y wget unzip

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 11076708
          log-accepted-android-sdk-licenses: false
          packages: "platform-tools platforms;android-34 build-tools;34.0.0"

      - name: Setup Xcode
        if: matrix.os == 'macos-latest'
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.1.0'

      - name: Clear npm and Yarn cache
        run: |
          npm cache clean --force
          yarn cache clean

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            /usr/local/android-sdk/build-tools
            /usr/local/android-sdk/platforms
            /usr/local/android-sdk/licenses
            ~/.konan/cache
          key: ${{ runner.os }}-dependencies-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-dependencies-

      - name: Grant Execute Permission for Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Build Project
        run: ./gradlew build

      - name: Publish Artifacts
        run: ./gradlew ${{ matrix.tasks }} --no-configuration-cache
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          SIGNING_KEYRING: ${{ secrets.SIGNING_KEYRING }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
